### PR TITLE
add more date ranges to the dropdown

### PR DESCRIPTION
**Pull request by aaronellington**
# Purpose
- Add more date ranges to the drop down
- Add a .gitattributes file to auto collapse generated files in the diff
 
Screen Shot 2019-04-03 at 11 21 00 AM

### CODE REVIEW

**Comment by aaronellington** [comment]
@KeshiaRose @benlower 

Howdy,  

What is the process for getting something merged and deployed here?

**Comment by KeshiaRose** [comment]
Hi @aaronellington, thanks for this great addition! Just wanted to let you know we are looking into this.

**Comment by KeshiaRose** [comment]
Hi @aaronellington,

In order to include your pull request, we will need you to sign a CLA. You can find the one for individuals [here](http://tableau.github.io/2017.02-TableauIndividualCLA.pdf) for your review. Could you please send your full name and mailing address to krose@tableau.com so we can send you the agreement for e-signature?

Take care,
Keshia

**Comment by aaronellington** [comment]
@KeshiaRose Email sent.

**Pull request closed without merging**
